import './globals.css'
import { Inter } from 'next/font/google'
import supabase from '@/utils/supabase'
import { AuthProvider } from '@/components/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const revalidate = 0

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const {
    data: { session },
    error,
  } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  )
}